language: node_js
node_js:
- '8'
deploy:
  skip_cleanup: true
script: npm run lint && npm run build
deploy:
  deploy:
  provider: s3
  access_key_id: "AKIAJ3XGUGQCE4SOJ3OA"
  secret_access_key:
    secure: "EMhkWO84xZDvCQQUonezIUvsI5H8xTUhP4zUHgV2syxaPYBaKyBi2LlFWZhfmnJW1SSrqpO/ZuvGeTcu39R61NsgIasH9xezwNju7J7yfxButxQ88pkZ6wHlWES/fB7buelcxhnburFqx3hKIfOlJMn35a5ihrsrdLwhPll+hR6QfGVE5h8FPEj5m1bzy0bpueVvfni7Z2/VnRe8/Qs1IjOiErugVWjWkQ9GVelkW/ZsvVA7xe3VMOid9615cHrk0wnZOYH4SrUwEVihnsRXSnFt18cOLArZ6nHcyanJuyPVN7wabTQMvE8Cckptp9rflvSHG43rrEzX4eTJ2orkjaZlBWu7zKjODgmv7YYgARViN5oowy7yRbScJ/kjbEnaPGz5am1EHjMVGi2b/4M//B9tW/Fra5QxlnDevkNFqUxyPeVsIxjwMhz1jGb4e3xJCFBLX4Aa8qA3+1xwhTLHJRCOCiF1bSDIRxgCEkQ6zfpKJk5YnKSZBtypNRQHHaPwDq6lbMusGnUzIbvunIqZ8tzySeLEZxbLCuZST0ep97qKRGmb8fdo628Y2aqsRc4putRD0AvHoSjKw1o1pi3rXwyfTZIwcI8Spvi7nk3VSk270LXbw084s4smcFwgdMpFdw9rWL5KL8vckaDHpPbaxqWBbqcMcNcxEVMMIhtq/xg="
  bucket: "sprit.cloud"
  skip_cleanup: true
  acl: public_read
  region: eu-west-1
  local_dir: dist
